# Site settings
title: Zaid Akram Mughal
email: zaidakrammughal@gmail.com
url: https://zaidakram.github.io
skills: "Full-Stack Engineer"
meta_author: Zaid Akram Mughal

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 34495E
  primary-rgb: "52,73,94"
  secondary: 34495E
  secondary-dark: 34495E

# Footer settings
footer:
  copyright: zaidakram.com
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/zaidakram
  - title: bitbucket
    url: https://bitbucket.org/zaidakram
  - title: linkedin
    url: linkedin.com/in/zaidakram
  - title: google-plus
    url: https://plus.google.com/+ZaidMughal


# Postal address (add as many lines as necessary)
address:
  - line: Bahria Town
  - line: Lahore, Pakistan

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
